//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 公司管理系统Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class action
    {
        public int actionId { get; set; }
        public Nullable<int> actionTypeID { get; set; }
        public string actionhead { get; set; }
        public string actionresult { get; set; }
        public Nullable<System.DateTime> actiontime { get; set; }
        public Nullable<int> actionneedmoney { get; set; }
        public Nullable<int> actionfactmoney { get; set; }
        public Nullable<int> UserId { get; set; }
        public string actiontype { get; set; }
    
        public virtual actionType actionType1 { get; set; }
        public virtual User User { get; set; }
    }
}
