//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 公司管理系统Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CompanyEntities : DbContext
    {
        public CompanyEntities()
            : base("name=CompanyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<action> action { get; set; }
        public virtual DbSet<actionType> actionType { get; set; }
        public virtual DbSet<Admin> Admin { get; set; }
        public virtual DbSet<ADType> ADType { get; set; }
        public virtual DbSet<@class> @class { get; set; }
        public virtual DbSet<culture> culture { get; set; }
        public virtual DbSet<detail> detail { get; set; }
        public virtual DbSet<Image> Image { get; set; }
        public virtual DbSet<Leave> Leave { get; set; }
        public virtual DbSet<money> money { get; set; }
        public virtual DbSet<Replay> Replay { get; set; }
        public virtual DbSet<ReplayType> ReplayType { get; set; }
        public virtual DbSet<score> score { get; set; }
        public virtual DbSet<system> system { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<web> web { get; set; }
    }
}
