//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 公司管理系统Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class detail
    {
        public int MonryId { get; set; }
        public string MonryResult { get; set; }
        public Nullable<int> sum { get; set; }
        public Nullable<System.DateTime> MoneyTime { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual User User { get; set; }
    }
}
