//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 公司管理系统Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class web
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public web()
        {
            this.Replay = new HashSet<Replay>();
        }
    
        public int webId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string webHead { get; set; }
        public string webResult { get; set; }
        public Nullable<System.DateTime> webtime { get; set; }
        public Nullable<int> like { get; set; }
        public Nullable<int> ReplayTypeID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Replay> Replay { get; set; }
        public virtual ReplayType ReplayType { get; set; }
        public virtual User User { get; set; }
    }
}
